library(tidyverse)

#Autosomes. Repeat for X and Y. 
#Read in eigenvalues generated by plink
pca <- read_table("./CB_CL_CNV.eigenvec", col_names = FALSE)
eigenval <- scan("./CB_CL_CNV.eigenval")

pca <- pca[,-1]
# set names
names(pca)[1] <- "ind"
names(pca)[2:ncol(pca)] <- paste0("PC", 1:(ncol(pca)-1))

#Add pop column and assign 
pca_pop <- pca %>%
  mutate(pop = case_when(
    grepl("BC", ind) ~ "Common",
    grepl("CB", ind) ~ "Common",
    grepl("CL", ind) ~ "White"))
view(pca_pop)    

pca_pop <- pca_pop %>%
  mutate(sex = case_when(
    grepl("F", ind) ~ "Female",
    grepl("M", ind) ~ "Male"))


#Calculate prop var
pve <- data.frame(PC = 1:20, pve = eigenval/sum(eigenval)*100)
pve

#Plot the first 2 PC
x<-ggplot() +
  geom_point(data = pca_pop, aes(x = PC1, y = PC2), shape=17, size=5, cex = 10) +
  geom_point(data = pca_pop, aes(x = PC1, y = PC2, colour = pop), shape=17, size=4) +
  scale_color_manual(values = alpha(c("White" = "deepskyblue3", "Common" = "green3"),.8)) +
  xlab("PC1 (13.533%)") +
  ylab("PC2 (11.76%)") +
  theme_linedraw()+
  theme(legend.position = "none")
x
